# Generated by Django 6.0.6 on 2026-07-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0003_databasebackup'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupSettings',
            fields=[
                ('settings_id', models.AutoField(primary_key=True, serialize=False)),
                ('backup_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default='Sunday', max_length=20)),
                ('backup_time', models.TimeField(default='02:00:00')),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'BackupSettings',
            },
        ),
    ]
