# Generated by Django 6.0.6 on 2026-07-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0004_backupsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='backupsettings',
            name='auto_backup_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
