# Generated by Django 6.0.6 on 2026-07-02 12:35

import resident.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0005_backupsettings_auto_backup_enabled'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', resident.models.CustomUserManager()),
            ],
        ),
    ]
