# Generated by Django 6.0.6 on 2026-07-02 12:37

from django.db import migrations


def update_existing_superusers(apps, schema_editor):
    User = apps.get_model('resident', 'User')
    User.objects.filter(is_superuser=True).update(role='official')

def reverse_update_existing_superusers(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('resident', '0006_alter_user_managers'),
    ]

    operations = [
        migrations.RunPython(update_existing_superusers, reverse_update_existing_superusers),
    ]
